# Generated by Django 3.2.6 on 2022-11-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(max_length=255, null=True, upload_to='media/images'),
        ),
    ]
